# Generated by Django 4.0.2 on 2022-03-21 02:30

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address1', models.TextField(default='Address', max_length=1000)),
                ('Address2', models.TextField(default='Address', max_length=1000)),
                ('State', models.CharField(max_length=100)),
                ('Distt', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('Phone', models.IntegerField(default=91)),
            ],
        ),
        migrations.CreateModel(
            name='contactus_query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('ContactNo', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(max_length=255, verbose_name='Course Name')),
                ('CourseDetail', models.TextField(default=True, max_length=1000, verbose_name='Course Detail')),
                ('Eligibility', models.CharField(max_length=255)),
                ('CourseDuration_min', models.CharField(max_length=50, verbose_name='Course Duration Minimum')),
                ('CourseDuration_max', models.CharField(max_length=50, verbose_name='Course Duration Minimum')),
                ('AnnualFee', models.IntegerField(verbose_name='Annual Fee')),
                ('CourseImage', models.ImageField(blank=True, help_text='Maximum file size allowed is 100KB', upload_to='images/course/', validators=[blog.models.validate_image])),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='images/services/')),
            ],
        ),
        migrations.CreateModel(
            name='StuRegistrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname_reg', models.CharField(max_length=100, verbose_name='First Name')),
                ('Lname_reg', models.CharField(max_length=100, verbose_name='Last Name')),
                ('Address_reg', models.CharField(max_length=1000, verbose_name='Address')),
                ('Adhar_reg', models.IntegerField(verbose_name='Adhar No.')),
                ('gender_reg', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='male', max_length=50, verbose_name='Gender')),
                ('Email_reg', models.EmailField(max_length=254, verbose_name='E-Mail Address')),
                ('Phone_reg', models.IntegerField(verbose_name='Phone')),
                ('Course_reg', models.CharField(choices=[('B.A', 'B.A'), ('BBA', 'BBA'), ('B.Com', 'B.Com'), ('M.A', 'M.A'), ('M.Sc.', 'M.Sc.'), ('MBA', 'MBA'), ('MCA', 'MCA'), ('Diploma', 'Diploma')], max_length=100, verbose_name='Course')),
                ('Uni_reg', models.CharField(choices=[('Subharti University, Meerut', 'Subharti University, Meerut'), ('JNU , Jaipur', 'JNU , Jaipur'), ('Himalayan Garhwal University', 'HGU')], max_length=100, verbose_name='University')),
                ('date_reg', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='Null', upload_to='images/post/')),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
