# Generated by Django 3.0.2 on 2020-03-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_register',
            name='City',
        ),
        migrations.RemoveField(
            model_name='user_register',
            name='ClassName',
        ),
        migrations.RemoveField(
            model_name='user_register',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='user_register',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='user_register',
            name='PinCode',
        ),
        migrations.RemoveField(
            model_name='user_register',
            name='SchoolName',
        ),
        migrations.AddField(
            model_name='user_register',
            name='Name',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user_register',
            name='Query',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='user_register',
            name='Subject',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='Address',
            field=models.CharField(default=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='ContactNo',
            field=models.IntegerField(default=True),
        ),
    ]
