# Generated by Django 4.0.2 on 2022-03-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_services_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=0, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sturegistrations',
            name='Course_reg',
            field=models.CharField(choices=[('B.A', 'B.A'), ('BBA', 'BBA'), ('B.Com', 'B.Com'), ('M.A', 'M.A'), ('M.Sc.', 'M.Sc.'), ('MBA', 'MBA'), ('MCA', 'MCA'), ('Diploma', 'Diploma'), ('Others', 'Others')], max_length=100, verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='sturegistrations',
            name='Uni_reg',
            field=models.CharField(choices=[('Subharti University, Meerut', 'Subharti University, Meerut'), ('JNU , Jaipur', 'JNU , Jaipur'), ('Himalayan Garhwal University', 'HGU'), ('Others', 'Others')], max_length=100, verbose_name='University'),
        ),
    ]
