# Generated by Django 3.0.2 on 2020-03-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200304_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='null', upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_register',
            name='Address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='ContactNo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='Query',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='Subject',
            field=models.CharField(max_length=200),
        ),
    ]
