# Generated by Django 3.0.2 on 2020-05-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_userprofileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemID', models.CharField(max_length=15)),
                ('ItemName', models.CharField(max_length=50)),
                ('Config', models.TextField(max_length=500)),
                ('Brand', models.CharField(max_length=50)),
                ('Model', models.CharField(max_length=50)),
                ('Dop', models.DateField()),
                ('Warranty', models.IntegerField()),
                ('Vendor', models.CharField(max_length=200)),
                ('Invoice', models.CharField(max_length=100)),
                ('InvoicePic', models.ImageField(upload_to='')),
                ('Remark', models.CharField(max_length=200)),
            ],
        ),
    ]
