# Generated by Django 3.0.2 on 2020-05-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_itemmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaster',
            name='ItemPrice',
            field=models.FloatField(default=True),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='ItemQty',
            field=models.IntegerField(default=True),
        ),
    ]
