# Generated by Django 3.0.2 on 2020-05-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200504_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='Brand',
            field=models.CharField(choices=[('orange', 'Oranges'), ('cantaloupe', 'Cantaloupes'), ('mango', 'Mangoes'), ('honeydew', 'Honeydews')], max_length=100),
        ),
    ]
