# Generated by Django 3.0.2 on 2020-05-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200504_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(max_length=1000)),
                ('about_img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='Brand',
            field=models.CharField(choices=[('1', 'HP'), ('2', 'Lenovo'), ('3', 'DELL'), ('4', 'HCL'), ('5', 'IBM')], max_length=100),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='ItemID',
            field=models.CharField(choices=[('1', 'comp001'), ('2', 'Prin001'), ('3', 'Scan001'), ('4', 'Proj001'), ('5', 'Lapt001')], max_length=15),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='ItemName',
            field=models.CharField(choices=[('1', 'Computer System'), ('2', 'Printer'), ('3', 'Scanner'), ('4', 'Projector'), ('5', 'Laptop')], max_length=50),
        ),
    ]
