# Generated by Django 3.0.2 on 2020-05-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200505_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='about_head',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
