# Generated by Django 3.0.2 on 2020-05-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_aboutus_about_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='about_head',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
