# Generated by Django 3.0.2 on 2020-05-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200505_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firm', models.CharField(default=False, max_length=50)),
                ('FirmLogo', models.ImageField(upload_to='')),
            ],
        ),
    ]
