# Generated by Django 3.0.2 on 2020-05-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_firmname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='about_head',
            field=models.CharField(default='About ...', max_length=50),
        ),
        migrations.AlterField(
            model_name='firmname',
            name='Firm',
            field=models.CharField(default='Company Name', max_length=50),
        ),
    ]
