# Generated by Django 3.0.2 on 2020-05-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200505_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='about',
            field=models.TextField(max_length=10000),
        ),
    ]
