# Generated by Django 3.0.2 on 2020-05-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200506_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address1', models.TextField(default='Address', max_length=1000)),
                ('Address2', models.TextField(default='Address', max_length=1000)),
                ('State', models.CharField(max_length=100)),
                ('Distt', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
