# Generated by Django 3.0.2 on 2020-05-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='Phone',
            field=models.IntegerField(default=91),
        ),
    ]
