# Generated by Django 3.0.2 on 2020-05-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_contactus_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_register',
            old_name='Query',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='user_register',
            name='Subject',
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='ItemID',
            field=models.CharField(choices=[('comp001', 'Computer'), ('Prin001', 'Printer'), ('Scan001', 'Scanner'), ('Proj001', 'Projector'), ('Lapt001', 'Laptop')], max_length=15),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='ItemName',
            field=models.CharField(choices=[('Computer System', 'Computer System'), ('2', 'Printer'), ('3', 'Scanner'), ('4', 'Projector'), ('5', 'Laptop')], max_length=50),
        ),
    ]
