# Generated by Django 3.0.2 on 2020-05-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200517_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmname',
            name='main_slider_img',
            field=models.ImageField(default='nul', upload_to=''),
        ),
    ]
