# Generated by Django 3.0.2 on 2020-05-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_firmname_main_slider_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmname',
            name='main_slider_txt',
            field=models.CharField(default='About', max_length=500),
        ),
    ]
