# Generated by Django 3.0.2 on 2020-05-21 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_firmname_main_slider_txt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FirmName',
            new_name='SiteSetting',
        ),
        migrations.RenameField(
            model_name='sitesetting',
            old_name='main_slider_txt',
            new_name='main_slider_mission',
        ),
    ]
