# Generated by Django 3.0.2 on 2020-05-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_delete_userprofileinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/post/'),
        ),
    ]
