# Generated by Django 3.0.2 on 2020-05-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200521_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='FirmLogo',
            field=models.ImageField(upload_to='images/site_sett_img/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='main_slider_img',
            field=models.ImageField(default='nul', upload_to='images/site_sett_img/'),
        ),
    ]
