# Generated by Django 3.0.2 on 2020-05-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20200521_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='about_img',
            field=models.ImageField(upload_to='images/about_img/'),
        ),
    ]
