# Generated by Django 3.0.2 on 2020-06-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200521_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
    ]
