# Generated by Django 3.0.2 on 2020-06-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20200622_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='Config',
            field=models.TextField(max_length=500, verbose_name='Configuration'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='InvoicePic',
            field=models.ImageField(upload_to='', verbose_name='Invoice Image'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='ItemID',
            field=models.CharField(choices=[('comp001', 'Computer'), ('Prin001', 'Printer'), ('Scan001', 'Scanner'), ('Proj001', 'Projector'), ('Lapt001', 'Laptop')], max_length=15, verbose_name='Item Id'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='ItemName',
            field=models.CharField(choices=[('Computer System', 'Computer System'), ('2', 'Printer'), ('3', 'Scanner'), ('4', 'Projector'), ('5', 'Laptop')], max_length=50, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='ItemPrice',
            field=models.FloatField(default=True, verbose_name='Item Price'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='ItemQty',
            field=models.IntegerField(default=True, verbose_name='Item Quantity'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='Warranty',
            field=models.IntegerField(verbose_name='Item Name'),
        ),
    ]
