# Generated by Django 3.0.2 on 2020-06-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20200622_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='Warranty',
            field=models.IntegerField(verbose_name='Item Warranty'),
        ),
    ]
