# Generated by Django 3.0.2 on 2020-06-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20200622_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmaster',
            name='ItemID',
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='ItemName',
            field=models.CharField(choices=[('Computer System', 'Computer System'), ('Printer', 'Printer'), ('Scanner', 'Scanner'), ('Projector', 'Projector'), ('Laptop', 'Laptop')], max_length=50, verbose_name='Item Name'),
        ),
    ]
