# Generated by Django 3.0.2 on 2020-06-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20200622_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaster',
            name='serial',
            field=models.CharField(default=True, max_length=50, verbose_name='Item Serial No'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='Dop',
            field=models.DateField(verbose_name='Purchase Date'),
        ),
    ]
