# Generated by Django 3.0.2 on 2020-07-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20200622_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='Brand',
            field=models.CharField(choices=[('HP', 'HP'), ('Lenovo', 'Lenovo'), ('DELL', 'DELL'), ('HCL', 'HCL'), ('IBM', 'IBM')], max_length=100),
        ),
    ]
