# Generated by Django 3.0.2 on 2020-07-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20200719_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_reg', models.DateTimeField(auto_now_add=True)),
                ('Fname_reg', models.CharField(max_length=100)),
                ('Lname_reg', models.CharField(max_length=100)),
                ('Address_reg', models.CharField(max_length=1000)),
                ('Adhar_reg', models.IntegerField()),
                ('Email_reg', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('Phone_reg', models.IntegerField(default=91)),
                ('Course_reg', models.CharField(max_length=100)),
                ('Uni_reg', models.CharField(max_length=100)),
            ],
        ),
    ]
