# Generated by Django 3.0.2 on 2020-07-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='Date_reg',
        ),
    ]
