# Generated by Django 3.0.2 on 2020-07-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_remove_register_date_reg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='registrations',
        ),
    ]
