# Generated by Django 3.0.2 on 2020-07-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20200721_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='Phone_reg',
            field=models.CharField(max_length=10),
        ),
    ]
