# Generated by Django 3.0.2 on 2020-07-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20200722_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='Phone_reg',
            field=models.IntegerField(),
        ),
    ]
