# Generated by Django 3.0.2 on 2020-07-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20200722_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='date_reg',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registrations',
            name='gender_reg',
            field=models.CharField(default='male', max_length=6),
        ),
    ]
