# Generated by Django 3.0.2 on 2020-07-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20200723_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(max_length=50, verbose_name='Course Name')),
                ('Eligibility', models.CharField(max_length=100)),
                ('CourseDuration_min', models.CharField(max_length=50, verbose_name='Course Duration Minimum')),
                ('CourseDuration_max', models.CharField(max_length=50, verbose_name='Course Duration Minimum')),
                ('AnnualFee', models.IntegerField(verbose_name='Annual Fee')),
            ],
        ),
        migrations.DeleteModel(
            name='ItemMaster',
        ),
    ]
