# Generated by Django 3.0.2 on 2020-07-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20200723_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Eligibility',
            field=models.CharField(max_length=255),
        ),
    ]
