# Generated by Django 3.0.2 on 2020-07-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_auto_20200723_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='CourseName',
            field=models.CharField(max_length=255, verbose_name='Course Name'),
        ),
    ]
