# Generated by Django 3.0.8 on 2020-08-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_auto_20200723_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='CourseDetail',
            field=models.TextField(default=True, max_length=1000, verbose_name='Course Detail'),
        ),
        migrations.AddField(
            model_name='course',
            name='CourseImage',
            field=models.ImageField(default='null', upload_to='images/course/'),
        ),
    ]
