# Generated by Django 3.1.2 on 2020-10-31 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='slug',
        ),
    ]
